# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 1101, 691))
        self.frame.setStyleSheet("border:none;     \n"
"border: 2px solid rgb(255, 255, 255);   /* 添加2px的白色框 */\n"
"width: 100px;    \n"
"height: 30px;     \n"
"\n"
"background-color: rgb(52, 52, 52);  \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label.setObjectName("label")
        self.Month = QtWidgets.QLineEdit(self.frame)
        self.Month.setGeometry(QtCore.QRect(140, 100, 161, 31))
        self.Month.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.Month.setText("")
        self.Month.setObjectName("Month")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 40, 171, 41))
        self.label_4.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52)")
        self.label_4.setObjectName("label_4")
        self.hidden_button = QtWidgets.QPushButton(self.frame)
        self.hidden_button.setGeometry(QtCore.QRect(1030, 10, 31, 31))
        self.hidden_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.hidden_button.setObjectName("hidden_button")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(1060, 10, 31, 31))
        self.close_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.close_button.setObjectName("close_button")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setGeometry(QtCore.QRect(330, 50, 751, 621))
        self.tableView.setStyleSheet("    color: black;                                       /*表格内文字颜色*/\n"
"    gridline-color: black;                              /*表格内框颜色*/\n"
"    background-color: rgb(108, 108, 108);               /*表格内背景色*/\n"
"    alternate-background-color: rgb(64, 64, 64);\n"
"    selection-color: while;                             /*选中区域的文字颜色*/\n"
"    selection-background-color: rgb(77, 77, 77);        /*选中区域的背景色*/\n"
"    border: 2px groove gray;\n"
"    border-radius: 0px;\n"
"    padding: 2px 4px;")
        self.tableView.setObjectName("tableView")
        self.Update = QtWidgets.QPushButton(self.frame)
        self.Update.setGeometry(QtCore.QRect(30, 550, 111, 41))
        self.Update.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Update.setObjectName("Update")
        self.rmv = QtWidgets.QPushButton(self.frame)
        self.rmv.setGeometry(QtCore.QRect(180, 550, 111, 41))
        self.rmv.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.rmv.setObjectName("rmv")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.label_2.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 91, 31))
        self.label_5.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 91, 31))
        self.label_6.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.label_7.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 91, 31))
        self.label_8.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_8.setObjectName("label_8")
        self.Eno = QtWidgets.QLineEdit(self.frame)
        self.Eno.setGeometry(QtCore.QRect(140, 140, 161, 31))
        self.Eno.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.Eno.setText("")
        self.Eno.setObjectName("Eno")
        self.attendace_cnt = QtWidgets.QLineEdit(self.frame)
        self.attendace_cnt.setGeometry(QtCore.QRect(140, 180, 161, 31))
        self.attendace_cnt.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.attendace_cnt.setText("")
        self.attendace_cnt.setObjectName("attendace_cnt")
        self.askfor_cnt = QtWidgets.QLineEdit(self.frame)
        self.askfor_cnt.setGeometry(QtCore.QRect(140, 220, 161, 31))
        self.askfor_cnt.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.askfor_cnt.setText("")
        self.askfor_cnt.setObjectName("askfor_cnt")
        self.notin_cnt = QtWidgets.QLineEdit(self.frame)
        self.notin_cnt.setGeometry(QtCore.QRect(140, 260, 161, 31))
        self.notin_cnt.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.notin_cnt.setText("")
        self.notin_cnt.setObjectName("notin_cnt")
        self.late_cnt = QtWidgets.QLineEdit(self.frame)
        self.late_cnt.setGeometry(QtCore.QRect(140, 300, 161, 31))
        self.late_cnt.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.late_cnt.setText("")
        self.late_cnt.setObjectName("late_cnt")
        self.Query = QtWidgets.QPushButton(self.frame)
        self.Query.setGeometry(QtCore.QRect(30, 500, 111, 41))
        self.Query.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Query.setObjectName("Query")
        self.Add = QtWidgets.QPushButton(self.frame)
        self.Add.setGeometry(QtCore.QRect(180, 500, 111, 41))
        self.Add.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Add.setObjectName("Add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">出勤月份</span></p></body></html>"))
        self.Month.setPlaceholderText(_translate("MainWindow", "必填"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">出勤信息</span></p></body></html>"))
        self.hidden_button.setText(_translate("MainWindow", "－"))
        self.close_button.setText(_translate("MainWindow", "×"))
        self.Update.setText(_translate("MainWindow", "修改"))
        self.rmv.setText(_translate("MainWindow", "删除"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">员工编号</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">出勤次数</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">请假次数</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">缺勤次数</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">迟到次数</span></p></body></html>"))
        self.Eno.setPlaceholderText(_translate("MainWindow", "必填"))
        self.Query.setText(_translate("MainWindow", "查询"))
        self.Add.setText(_translate("MainWindow", "添加"))
