# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1101, 691))
        self.frame.setStyleSheet("border:none;     \n"
"border: 2px solid rgb(255, 255, 255);   /* 添加2px的白色框 */\n"
"width: 100px;    \n"
"height: 30px;     \n"
"\n"
"background-color: rgb(52, 52, 52);  \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label.setObjectName("label")
        self.Eno = QtWidgets.QLineEdit(self.frame)
        self.Eno.setGeometry(QtCore.QRect(140, 100, 161, 31))
        self.Eno.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.Eno.setText("")
        self.Eno.setObjectName("Eno")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 40, 191, 51))
        self.label_4.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52)")
        self.label_4.setObjectName("label_4")
        self.hidden_button = QtWidgets.QPushButton(self.frame)
        self.hidden_button.setGeometry(QtCore.QRect(1030, 10, 31, 31))
        self.hidden_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.hidden_button.setObjectName("hidden_button")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(1060, 10, 31, 31))
        self.close_button.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.close_button.setObjectName("close_button")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setGeometry(QtCore.QRect(330, 50, 751, 621))
        self.tableView.setStyleSheet("    color: black;                                       /*表格内文字颜色*/\n"
"    gridline-color: black;                              /*表格内框颜色*/\n"
"    background-color: rgb(108, 108, 108);               /*表格内背景色*/\n"
"    alternate-background-color: rgb(64, 64, 64);\n"
"    selection-color: while;                             /*选中区域的文字颜色*/\n"
"    selection-background-color: rgb(77, 77, 77);        /*选中区域的背景色*/\n"
"    border: 2px groove gray;\n"
"    border-radius: 0px;\n"
"    padding: 2px 4px;")
        self.tableView.setObjectName("tableView")
        self.updateE = QtWidgets.QPushButton(self.frame)
        self.updateE.setGeometry(QtCore.QRect(30, 550, 111, 41))
        self.updateE.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.updateE.setObjectName("updateE")
        self.remv = QtWidgets.QPushButton(self.frame)
        self.remv.setGeometry(QtCore.QRect(180, 550, 111, 41))
        self.remv.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.remv.setObjectName("remv")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.label_2.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 220, 101, 31))
        self.label_5.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 260, 111, 31))
        self.label_6.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 300, 81, 31))
        self.label_7.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 340, 91, 31))
        self.label_8.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(40, 380, 71, 31))
        self.label_9.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_9.setObjectName("label_9")
        self.Ename = QtWidgets.QLineEdit(self.frame)
        self.Ename.setGeometry(QtCore.QRect(140, 180, 161, 31))
        self.Ename.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.Ename.setText("")
        self.Ename.setObjectName("Ename")
        self.birth = QtWidgets.QLineEdit(self.frame)
        self.birth.setGeometry(QtCore.QRect(140, 220, 161, 31))
        self.birth.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.birth.setText("")
        self.birth.setObjectName("birth")
        self.IDcard = QtWidgets.QLineEdit(self.frame)
        self.IDcard.setGeometry(QtCore.QRect(140, 260, 161, 31))
        self.IDcard.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.IDcard.setText("")
        self.IDcard.setObjectName("IDcard")
        self.birthaddress = QtWidgets.QLineEdit(self.frame)
        self.birthaddress.setGeometry(QtCore.QRect(140, 300, 161, 31))
        self.birthaddress.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.birthaddress.setText("")
        self.birthaddress.setObjectName("birthaddress")
        self.phone = QtWidgets.QLineEdit(self.frame)
        self.phone.setGeometry(QtCore.QRect(140, 340, 161, 31))
        self.phone.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.nowlive = QtWidgets.QLineEdit(self.frame)
        self.nowlive.setGeometry(QtCore.QRect(140, 380, 161, 31))
        self.nowlive.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.nowlive.setText("")
        self.nowlive.setObjectName("nowlive")
        self.queryE = QtWidgets.QPushButton(self.frame)
        self.queryE.setGeometry(QtCore.QRect(30, 500, 111, 41))
        self.queryE.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.queryE.setObjectName("queryE")
        self.addE = QtWidgets.QPushButton(self.frame)
        self.addE.setGeometry(QtCore.QRect(180, 500, 111, 41))
        self.addE.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.addE.setObjectName("addE")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(40, 140, 91, 31))
        self.label_12.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_12.setObjectName("label_12")
        self.Dno = QtWidgets.QLineEdit(self.frame)
        self.Dno.setGeometry(QtCore.QRect(140, 140, 161, 31))
        self.Dno.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.Dno.setText("")
        self.Dno.setObjectName("Dno")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">员工编号</span></p></body></html>"))
        self.Eno.setPlaceholderText(_translate("MainWindow", "必填 一个整数"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">员工信息</span></p></body></html>"))
        self.hidden_button.setText(_translate("MainWindow", "－"))
        self.close_button.setText(_translate("MainWindow", "×"))
        self.updateE.setText(_translate("MainWindow", "修改"))
        self.remv.setText(_translate("MainWindow", "删除"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">员工姓名</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">出生日期</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">身份证号码</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">出生地</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">联系电话</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">现住址</span></p></body></html>"))
        self.Ename.setPlaceholderText(_translate("MainWindow", "必填"))
        self.IDcard.setPlaceholderText(_translate("MainWindow", "必填"))
        self.phone.setPlaceholderText(_translate("MainWindow", "必填"))
        self.queryE.setText(_translate("MainWindow", "查询"))
        self.addE.setText(_translate("MainWindow", "添加"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">所属部门</span></p></body></html>"))
        self.Dno.setPlaceholderText(_translate("MainWindow", "必填"))
