# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'salary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1111, 701))
        self.frame.setStyleSheet("border:none;     \n"
"border: 2px solid rgb(255, 255, 255);   /* 添加2px的白色框 */\n"
"width: 100px;    \n"
"height: 30px;     \n"
"\n"
"background-color: rgb(52, 52, 52);  \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label.setObjectName("label")
        self.month = QtWidgets.QLineEdit(self.frame)
        self.month.setGeometry(QtCore.QRect(150, 100, 161, 31))
        self.month.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.month.setText("")
        self.month.setObjectName("month")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 181, 61))
        self.label_4.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52)")
        self.label_4.setObjectName("label_4")
        self.button_hidden = QtWidgets.QPushButton(self.frame)
        self.button_hidden.setGeometry(QtCore.QRect(1030, 10, 31, 31))
        self.button_hidden.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.button_hidden.setObjectName("button_hidden")
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setGeometry(QtCore.QRect(1060, 10, 31, 31))
        self.button_close.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color:  rgb(52, 52, 52);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(52, 52, 52);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.button_close.setObjectName("button_close")
        self.tableView = QtWidgets.QTableView(self.frame)
        self.tableView.setGeometry(QtCore.QRect(330, 50, 751, 621))
        self.tableView.setStyleSheet("    color: black;                                       /*表格内文字颜色*/\n"
"    gridline-color: black;                              /*表格内框颜色*/\n"
"    background-color: rgb(108, 108, 108);               /*表格内背景色*/\n"
"    alternate-background-color: rgb(64, 64, 64);\n"
"    selection-color: while;                             /*选中区域的文字颜色*/\n"
"    selection-background-color: rgb(77, 77, 77);        /*选中区域的背景色*/\n"
"    border: 2px groove gray;\n"
"    border-radius: 0px;\n"
"    padding: 2px 4px;")
        self.tableView.setObjectName("tableView")
        self.Update = QtWidgets.QPushButton(self.frame)
        self.Update.setGeometry(QtCore.QRect(30, 550, 111, 41))
        self.Update.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Update.setObjectName("Update")
        self.rmv = QtWidgets.QPushButton(self.frame)
        self.rmv.setGeometry(QtCore.QRect(180, 550, 111, 41))
        self.rmv.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.rmv.setObjectName("rmv")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.label_2.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 91, 31))
        self.label_5.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 71, 31))
        self.label_6.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 71, 31))
        self.label_7.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 141, 31))
        self.label_8.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"border-color:rgb(52, 52, 52);")
        self.label_8.setObjectName("label_8")
        self.eno = QtWidgets.QLineEdit(self.frame)
        self.eno.setGeometry(QtCore.QRect(150, 140, 161, 31))
        self.eno.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.eno.setText("")
        self.eno.setObjectName("eno")
        self.base_salary = QtWidgets.QLineEdit(self.frame)
        self.base_salary.setGeometry(QtCore.QRect(150, 180, 161, 31))
        self.base_salary.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.base_salary.setText("")
        self.base_salary.setObjectName("base_salary")
        self.money_give = QtWidgets.QLineEdit(self.frame)
        self.money_give.setGeometry(QtCore.QRect(150, 220, 161, 31))
        self.money_give.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.money_give.setText("")
        self.money_give.setObjectName("money_give")
        self.jiaban = QtWidgets.QLineEdit(self.frame)
        self.jiaban.setGeometry(QtCore.QRect(150, 260, 161, 31))
        self.jiaban.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.jiaban.setText("")
        self.jiaban.setObjectName("jiaban")
        self.kouchu = QtWidgets.QLineEdit(self.frame)
        self.kouchu.setGeometry(QtCore.QRect(150, 300, 161, 31))
        self.kouchu.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px;\n"
"color:rgb(186,186,186);")
        self.kouchu.setText("")
        self.kouchu.setObjectName("kouchu")
        self.Query = QtWidgets.QPushButton(self.frame)
        self.Query.setGeometry(QtCore.QRect(30, 500, 111, 41))
        self.Query.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Query.setObjectName("Query")
        self.Add = QtWidgets.QPushButton(self.frame)
        self.Add.setGeometry(QtCore.QRect(180, 500, 111, 41))
        self.Add.setStyleSheet("QPushButton{\n"
"    font: 20pt \"微软雅黑\";\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 3px solid rgb(0,0,0);\n"
"    border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px\n"
"}\n"
"")
        self.Add.setObjectName("Add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">工资月份</span></p></body></html>"))
        self.month.setPlaceholderText(_translate("MainWindow", "必填"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">薪资信息</span></p></body></html>"))
        self.button_hidden.setText(_translate("MainWindow", "－"))
        self.button_close.setText(_translate("MainWindow", "×"))
        self.Update.setText(_translate("MainWindow", "修改"))
        self.rmv.setText(_translate("MainWindow", "删除"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aaff;\">员工编号</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">基本工资</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">奖金</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">加班费</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#bababa;\">缺勤扣除工资</span></p></body></html>"))
        self.eno.setPlaceholderText(_translate("MainWindow", "必填"))
        self.Query.setText(_translate("MainWindow", "查询"))
        self.Add.setText(_translate("MainWindow", "添加"))
